### ISSUE TITLE
Hi kikto

### ISSUE THREAD

**Issue by rc3097** [kikito/md5.lua#3]
I would like to use your script to md5sum a file. However, it doesn't work really well. I read the file into a string, However, even I change the part of file. The value is same and different from the Linux md5sum

**Comment by kikito** [comment]
With the data you gave me there's very little I can do. You might be trying to open the file in text mode instead of in binary mode.

You can read more about that here: http://www.lua.org/pil/21.2.2.html

I will close down this issue now. If you need more help, feel free to reopen it (make sure that you include the code that you are using, the file you are testing, the linux version you are using, and the exact linux md5 command)

**Comment by kikito** [comment]
Hello @rc3097 ,

Recently we discovered an issue with Lua 5.2 (not LuaJIT or Lua 5.1) - it was not calculating the md5 correctly for big files (details in #4). If you where using Lua 5.2, it's possible that your problem was related to this. Please try the new version in master (I have also pushed a new version to luarocks).

Regards!

**Comment by rc3097** [comment]
I found the way to figure out that. Tell you later
